// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0kV-MK40EIEtyP5IweWQ8rFULHBdY4RY',
    appId: '1:1086471151087:web:1a41ac439cbbbec62f6a1a',
    messagingSenderId: '1086471151087',
    projectId: 'else7a-tmam',
    authDomain: 'else7a-tmam.firebaseapp.com',
    storageBucket: 'else7a-tmam.appspot.com',
    measurementId: 'G-W81XYM46FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMb0xPtJGyTgxgGzzq2Qe7o2h36y-dsLk',
    appId: '1:1086471151087:android:e1d8d62a26fb45d12f6a1a',
    messagingSenderId: '1086471151087',
    projectId: 'else7a-tmam',
    storageBucket: 'else7a-tmam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyFQKHcJlcH0po1XNIAH1smrtqRZ1KHOI',
    appId: '1:1086471151087:ios:d37198a5885f72152f6a1a',
    messagingSenderId: '1086471151087',
    projectId: 'else7a-tmam',
    storageBucket: 'else7a-tmam.appspot.com',
    iosClientId: '1086471151087-t2r2qkouqvslv7huk2btd8s7ggqvvg3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.else7aTamam',
  );
}
